name: omeka-s-dev

services:
  caddy:
    build:
      context: caddy
      dockerfile: Dockerfile.dev
    depends_on:
      - omeka-s-app
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    environment:
      OMEKA_SERVICE: omeka-s-app
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'
    networks:
      - omeka-s-network


  omeka-s-app:
    build:
      context: omeka-s
      dockerfile: Dockerfile
      target: main
    depends_on:
      omeka-s-db:
        condition: service_healthy
    volumes:
      - omeka-s-app:/var/www/html
    secrets:
      - mariadb_password
      - omeka_admin_user
      - omeka_admin_email
      - omeka_admin_password
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        export MARIADB_PASSWORD="$(cat /run/secrets/mariadb_password)"
        export OMEKA_ADMIN_USER="$(cat /run/secrets/omeka_admin_user)"
        export OMEKA_ADMIN_EMAIL="$(cat /run/secrets/omeka_admin_email)"
        export OMEKA_ADMIN_PASSWORD="$(cat /run/secrets/omeka_admin_password)"
        envsubst < /var/www/html/config/config.tpl > /var/www/html/config/config.json
        envsubst < /var/www/html/public/config/database.ini.tpl > /var/www/html/public/config/database.ini
        exec docker-php-entrypoint apache2-foreground
    environment:
      MARIADB_DATABASE: omekas
      MARIADB_USER: omekas
      MARIADB_HOST: omeka-s-db
      MARIADB_PORT: 3306
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - omeka-s-network
    restart: unless-stopped

  omeka-s-db:
    image: mariadb:12.2.1-noble-rc
    volumes:
      - omeka-s-db:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    secrets:
      - mariadb_password
      - mariadb_root_password
    environment:
      MARIADB_DATABASE: omekas
      MARIADB_USER: omekas
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
    networks:
      - omeka-s-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 10

networks:
  omeka-s-network:
    driver: bridge
    name: "${COMPOSE_PROJECT_NAME}-network"

volumes:
  omeka-s-db:
  omeka-s-app:
  caddy-data:
  caddy-config:

secrets:
  mariadb_password:
    file: secrets/mariadb_password.txt
  mariadb_root_password:
    file: secrets/mariadb_root_password.txt
  omeka_admin_user:
    file: secrets/omeka_admin_user.txt
  omeka_admin_email:
    file: secrets/omeka_admin_email.txt
  omeka_admin_password:
    file: secrets/omeka_admin_password.txt
