name: omeka-s-build

services:

  omeka-s-app-build:
    build:
      context: omeka-s
      target: builder
      dockerfile: Dockerfile
    depends_on:
      omeka-s-db:
        condition: service_healthy
    volumes:
      - omeka-s-app:/var/www/html
      - ./db-init:/db-init
      - ./omeka-s/assets/php-init:/php-init
    secrets:
      - mariadb_build_password
      - omeka_build_admin_user
      - omeka_build_admin_email
      - omeka_build_admin_password
      - omeka_build_site_slug
    environment:
      MARIADB_DATABASE: omekas
      MARIADB_USER: omekas
      MARIADB_HOST: omeka-s-db
      MARIADB_PORT: 3306
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - omeka-s-network
    command: /build-entrypoint.sh

  omeka-s-db:
    image: mariadb:12.2.1-noble-rc
    volumes:
      - omeka-s-db:/var/lib/mysql
    secrets:
      - mariadb_build_password
      - mariadb_build_root_password
    environment:
      MARIADB_DATABASE: omekas
      MARIADB_USER: omekas
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_build_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_build_root_password
    networks:
      - omeka-s-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 10

networks:
  omeka-s-network:
    driver: bridge
    name: "${COMPOSE_PROJECT_NAME}-network"

volumes:
  omeka-s-db:
  omeka-s-app:

secrets:
  mariadb_build_password:
    file: secrets/build/mariadb_password.txt
  mariadb_build_root_password:
    file: secrets/build/mariadb_root_password.txt
  omeka_build_admin_user:
    file: secrets/build/omeka_admin_user.txt
  omeka_build_admin_email:
    file: secrets/build/omeka_admin_email.txt
  omeka_build_admin_password:
    file: secrets/build/omeka_admin_password.txt
  omeka_build_site_slug:
    file: secrets/build/omeka_site_slug.txt
